remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Armin Kobilica
description: Ph.D. Candidate, KFUPM <a href="https://www.linkedin.com/in/armin-kobilica-223b2a3a/"><img width="8%" height="8%" src="https://img.icons8.com/ios-filled/50/000000/linkedin.png"/></a><a href='mailto:arminkobilica@gmail.com'><img width="8%" height="8%" src="https://img.icons8.com/external-kiranshastry-solid-kiranshastry/64/000000/external-email-interface-kiranshastry-solid-kiranshastry.png"/></a>
show_downloads: false
github:
  is_project_page: false